### ISSUE TITLE
Go module has a naming mismatch

### ISSUE THREAD

**Issue by staust** [bitrise-steplib/bitrise-step-restore-gradle-cache#7]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.2.3
- Is the issue reproducible with the latest version? YES / NO
- Does the issue happen sporadically, or every time? SPORADIC / EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

The current module name does not match convention. You can observe this when you try to execute the step via go:
```
go run github.com/bitrise-steplib/bitrise-step-restore-gradle-cache@latest

go: github.com/bitrise-steplib/bitrise-step-restore-gradle-cache@latest: github.com/bitrise-steplib/bitrise-step-restore-gradle-cache@v0.0.0-20230209151339-fd9ae1631400: parsing go.mod:
        module declares its path as: github.com/bitrise-steplib/steps-restore-gradle-cache
                but was required as: github.com/bitrise-steplib/bitrise-step-restore-gradle-cache
```

You should rename the module name in go.mod to: "github.com/bitrise-steplib/bitrise-step-restore-gradle-cache"

**Comment by ofalvai** [comment]
Ooops, the module declaration is indeed incorrect. What is your setup and use-case look like though? This does not come up when running the code as a Bitrise step, probably because [the step metadata](https://github.com/bitrise-steplib/bitrise-step-restore-gradle-cache/blob/main/step.yml#L33) declares the correct package.

**Comment by staust** [comment]
we have written our own private step for preparation processes of our source code. We call e.g. the cache actions via go directly in there as we are able to save some seconds there by running this in parallel of other stuff.

**Comment by ofalvai** [comment]
Oh, that's cool! In this case, I recommend using the `go-steputils/cache` [package](https://github.com/bitrise-io/go-steputils/tree/master/cache) directly, this step is just the [thin wrapper](https://github.com/bitrise-steplib/bitrise-step-restore-gradle-cache/blob/fd9ae1631400b4debd2a98ce93fe12c8e84f1661/step/step.go#L66-L71) around it anyway.

(But we'll fix this bug, thank you for raising it!)

**Comment by staust** [comment]
Thanks for the hint, will give it a try
